#!/bin/bash

### terminal color

sep='--------------------------------------------------------------------------------------------------------------------------------------'
echo -e "$sep"
for fgs in '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
        '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
        '  36m' '1;36m' '  37m' '1;37m';
do
        echo -en " ${fgs} " | awk '{printf "%-8s",$1}' 
done
echo;

for fgs in '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
        '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
        '  36m' '1;36m' '  37m' '1;37m';
do
        echo -en "\033[${fgs// /}iTi     \033[0m" 
done

echo -e "
${sep}\n
usage:  echo -e \"\e[[fg] tTt \e[0m\"
        eg. echo -e \"\e[1;31m tTt \e[0m\""

echo -n "        display:" && echo -e "\033[1;31m tTt \033[0m"
