#!/bin/bash

export LDF_DIR=$(dirname "$(echo "$0" | sed -e '')")

# load rcfile
rcfile="$LDF_DIR/ldfrc"
[ -r "${rcfile}" ] && source "${rcfile}"
export ldf_custom_rcfile="${HOME}/.ldfrc"
[ -r "${ldf_custom_rcfile}" ] && source "${ldf_custom_rcfile}"

logo(){
    echo '
   _          
  //  __/   /)
_(/__(_/(__//_
         _/   
         /)   
         `           
    '
}

fmt (){
    echo -e $1 | awk -F'\t' '{
        if (length($1) < 20) {
            printf "%-20s%s\n",$1,$2
        } else {
            print $1;
            printf "%-20s%s\n", "", $2
        }
    }'
}

fmt_title (){
    keyword_length=`echo "$1" |wc -c`
    let "prefix_length = (30-keyword_length) / 2"
    for i in `seq 0 ${prefix_length}` ;do
	    echo -n '-'
    done
    echo -n " $1 "
    let "suffix_length = keyword_length % 2 != 0 ? prefix_length+1: prefix_length"
    for i in `seq 0 $suffix_length` ;do
	    echo -n '-'
    done
    echo ''
}

find_commands(){
    for folder in `ls -l $1 | grep ^d | awk '{print $9}'` ;do
        tools_dir="$1/${folder}/tools"
        if [ ! -d ${tools_dir} ]; then
            continue;
        fi
        cmds=`ls -l ${tools_dir} | grep -v '^d' | awk '{print $9}'`
        if [ "${cmds}" = "" ]; then
            continue;
        fi

        fmt_title ${folder} 
        for cmd in ${cmds} ;do
            desc=`grep '^###' ${tools_dir}/${cmd} | cut -c 4-`
            if [ "${desc}" != ""  ]; then
                fmt "${cmd}\t:$desc"
                echo "${cmd}" >> $HOME/.ldf/cmds.cache
            fi
        done
        echo ''
    done

}

list() {
    rm -f $HOME/.ldf/cmds.cache 2>/dev/null
    mkdir $HOME/.ldf 2>/dev/null
    echo 'Available commands:'
    find_commands ${LDF_DIR}
    find_commands ${LDF_DIR}/custom
    exit 0;
}

uninstall() {
    echo -n "Uninstall ldf,(y)es or (n)o?"
    read choice < /dev/tty
    if [ "${choice}" = "y" ] && [ "${LDF_DIR}" != "/" ];then
	    cd ${LDF_DIR} && make uninstall && rm -rf ${LDF_DIR} && echo "ldf uninstall finished. Bye~"
    fi
    exit 0
}

if [ $# = 0 ];then
    logo
    fmt 'Usage '
    fmt " ldf list\t: show all commands \nldf command\t: execute a command\nldf update\t: update ldf\nldf uninstall\t: uninstall ldf"
    exit
fi

if [ "$1" = "list" ];then 
    list "$@"
fi

if [ "$1" = "uninstall" ]; then
    uninstall "$@"
fi

tools_dir=${LDF_DIR}/*/tools/
custom_tools_dir=${LDF_DIR}/custom/*/tools/
command_file=$1;shift
command=`find ${tools_dir} -maxdepth 1 -name ${command_file} `

if [ ! -f "${command}" ]; then
    command=`find ${custom_tools_dir} -maxdepth 1 -name ${command_file} `
    if [ ! -f "${command}" ]; then
	echo "${command_file} command not found!"
	exit 1;
    fi
fi

exec "${command}" "$@"

