#!/bin/bash

export tb_dir=$(dirname "$(echo "$0" | sed -e '')")

# load rcfile
rcfile="${tb_dir}/tbrc"
[ -r "${rcfile}" ] && source "${rcfile}"
export st_custom_rcfile="${HOME}/.tbrc"
[ -r "${st_custom_rcfile}" ] && source "${st_custom_rcfile}"

# load common libs functions
common_lib="${tb_dir}/common/lib/common-functions"
[ -r "${common_lib}" ] && source ${common_lib}

logo() {
    echo '
       _          
      //  __/   /)
    _(/__(_/(__//_
            _/   
            /)   
            `           
    '
}
usage() {
cat << EOF
$(fmt_bold USAGE)
tb list:       show all commands
tb command:    execute a command(such as color、stats)
tb update:     update tb
tb uninstall:  uninstall tb
EOF
}

find_commands() {
    for folder in `ls -l $1 | grep ^d | awk '{print $9}'` ;do
        tools_dir="$1/${folder}/tools"
        if [ ! -d ${tools_dir} ]; then
            continue;
        fi
        cmds=`ls -l ${tools_dir} | grep -v '^d' | awk '{print $9}'`
        if [ "${cmds}" = "" ]; then
            continue;
        fi

        fmt_title ${folder} 
        for cmd in ${cmds} ;do
            desc=`grep '^###' ${tools_dir}/${cmd} | cut -c 4-`
            if [ "${desc}" != ""  ]; then
                fmt_cmd "${cmd}\t:$desc"
                echo "${cmd}" >> $HOME/.tb/cmds.cache
            fi
        done
        echo ''
    done

}

list() {
    rm -f $HOME/.tb/cmds.cache 2>/dev/null
    mkdir $HOME/.tb 2>/dev/null
    echo 'Available commands:'
    find_commands ${tb_dir}
    find_commands ${tb_dir}/custom
    exit 0;
}

uninstall() {
    echo -n "Uninstall tb,(y)es or (n)o?"
    read choice < /dev/tty
    if [ "${choice}" = "y" ] && [ "${tb_dir}" != "/" ];then
	    cd ${tb_dir} && make uninstall && rm -rf ${tb_dir} && echo "tb uninstall finished. Bye~"
    fi
    exit 0
}

if [ $# = 0 ];then
    logo
    usage
    exit
fi

if [ "$1" = "list" ];then 
    list "$@"
fi

if [ "$1" = "uninstall" ]; then
    uninstall "$@"
fi

tools_dir=${tb_dir}/*/tools/
custom_tools_dir=${tb_dir}/custom/*/tools/
command_file=$1;shift
command=`find ${tools_dir} -maxdepth 1 -name ${command_file} `

if [ ! -f "${command}" ]; then
    command=`find ${custom_tools_dir} -maxdepth 1 -name ${command_file} `
    if [ ! -f "${command}" ]; then
	echo "${command_file} command not found!"
	exit 1;
    fi
fi

exec "${command}" "$@"

