#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
### 自动生成模型和字典信息markdown文档

import argparse
import os
import sys

import pymysql
import yaml

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))))

from custom.meta.lib.model_doc import persist_model_meta
from custom.meta.lib.dict_doc import persist_dict_meta


def get_config_file():
    parser = argparse.ArgumentParser()
    parser.description = '参数解析'
    parser.add_argument('-c', '--config_file', required=True, help='配置文件')
    args = parser.parse_args()
    return args.config_file


def get_config_data(yaml_file):
    # 打开yaml文件
    file = open(yaml_file, 'r', encoding="utf-8")
    file_data = file.read()
    file.close()

    # 将字符串转化为字典或列表
    return yaml.full_load(file_data)


if __name__ == "__main__":
    # 获取配置
    config_file = get_config_file()
    config_data = get_config_data(config_file)

    # 连接数据库
    mysql_password = input("请输入MYSQL_PASSWORD: ")
    db = pymysql.connect(host=config_data["mysql"]["mysql_host"], port=config_data["mysql"]["mysql_port"],
                         db=config_data["mysql"]["mysql_database"], user=config_data["mysql"]["mysql_username"],
                         password=mysql_password)
    db.autocommit(True)
    cursor = db.cursor()

    # 打开文件
    fo = open(os.getcwd() + "/meta_doc.md", "w")

    # 持久化模型原信息
    model_list = []
    model_desc_dict = {}
    dict_list = []
    if len(config_data["models"]) > 0:
        # 待处理模型
        for model in config_data["models"]:
            if model["name"] not in model_list:
                model_list.append(model["name"])
                model_desc_dict[model["name"]] = model["desc"]

        fo.write("## 模型信息\n\n")
        idx = 0
        while idx < len(model_list):
            model_key = model_list[idx]
            model_desc = model_desc_dict[model_key] if model_key in model_desc_dict else None

            # 模型字段文案备注
            model_field_desc = config_data["model_field_desc"]
            field_desc = model_field_desc[model_key] if model_key in model_field_desc else None
            relate_meta_list = persist_model_meta(cursor, model_key, model_desc, field_desc, fo)
            for relate_meta in relate_meta_list:
                if relate_meta.startswith("ysmy_"):
                    continue
                if not relate_meta.endswith("Dict") and relate_meta not in model_list:
                    model_list.append(relate_meta)
                if not relate_meta.endswith("BO") and not relate_meta.endswith("TO") and relate_meta not in dict_list:
                    dict_list.append(relate_meta)
            # 准备处理下一条
            idx = idx + 1

    # 持久化字典原信息
    if len(dict_list) > 0:
        fo.write("## 字典信息\n\n")
        for dict_key in dict_list:
            persist_dict_meta(cursor, dict_key, fo)

    # 文档生成完成
    print("文档已生成，地址：", os.getcwd() + "/meta_doc.md")
    # 关闭数据库 & 文件连接
    cursor.close()
    db.close()
    fo.close()
