#!/bin/bash

### 堆对象相关:dump heap到文件、显示jvm heap中top20的对象、显示Java堆详细信息、显示在F-Queue队列等待Finalizer线程执行finalizer方法的对象

usage() {
    cat <<EOF
Usage: moto $(basename $0) [OPTION] pid [arg]
堆对象相关:dump heap到文件、显示jvm heap中top20的对象、显示Java堆详细信息、显示在F-Queue队列等待Finalizer线程执行finalizer方法的对象
Example: moto $(basename $0) -dumplive 1234 

Options:
    -dump       ref:jmap -dump:format=b,file=heap.bin pid 生成堆转储快照dump文件
    -dumplive   ref:jmap -dump:live,format=b,file=heap.bin pid 生成堆活动的对象快照dump文件              
    -histo      ref:jmap -histo pid | sort -nr -k([arg]+1) | head -n 21;
                    jvm heap中top20的对象;0;参数：1:按实例数量排序,2:按内存占用排序，默认为1;1
    -histolive  ref:jmap -histo:live pid | sort -nr -k([arg]+1) | head -n 21; 
                    jvm heap中活动的top20的对象;0;参数：1:按实例数量排序,2:按内存占用排序，默认为1;1
    -heap       ref:jmap -heap; 显示Java堆详细信息
    -clstats       ref:jmap -clstats; 打印类加载器信息          
    -finalizerinfo ref:jmap -finalizerinfo; 显示在F-Queue队列等待Finalizer线程执行finalizer方法的对象       
EOF
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

cmd=""
flag="$1"
case "$flag" in
-h | --help)
    usage
    exit 0
    ;;
-dump)
    cmd="jmap -dump:format=b,file=heap.bin"
    ;;
-dumplive)
    cmd="jmap -dump:live,format=b,file=heap.bin"
    ;;
-histo)
    cmd="jmap -histo"
    ;;
-histolive)
    cmd="jmap -histo:live"
    ;;
-heap)
    cmd="jmap -heap"
    ;;
-clstats)
    cmd="jmap -clstats"
    ;;
-finalizerinfo)
    cmd="jmap -finalizerinfo"
    ;;
*)
    usage
    exit 1
    ;;
esac
pid=${2}
shift
shift

arg="${@}"
if [ $# -lt 1 ]; then
    case "$flag" in
    -dump | -dumplive | -heap | -clstats | -finalizerinfo)
        ${cmd} ${pid}
        ;;
    -histo | -histolive)
        col=${1:-2}
        ${cmd} ${pid} | sort -nr -k ${col} | head -n 21
        ;;
    *)
        usage
        exit 1
        ;;
    esac
fi
